"""rename users to publishers and update schema

Revision ID: 56f8ff3bf37e
Revises: 
Create Date: 2026-03-06 14:15:22.549679

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f8ff3bf37e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discoveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('smiles', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('molecular_weight', sa.Float(), nullable=False),
    sa.Column('publisher_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discoveries_id'), 'discoveries', ['id'], unique=False)
    op.create_index(op.f('ix_discoveries_molecular_weight'), 'discoveries', ['molecular_weight'], unique=False)
    op.create_index(op.f('ix_discoveries_smiles'), 'discoveries', ['smiles'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discoveries_smiles'), table_name='discoveries')
    op.drop_index(op.f('ix_discoveries_molecular_weight'), table_name='discoveries')
    op.drop_index(op.f('ix_discoveries_id'), table_name='discoveries')
    op.drop_table('discoveries')
    # ### end Alembic commands ###
