"""add constraints to publisher model

Revision ID: e194aa5ffae1
Revises: 1a8b218ba8b9
Create Date: 2026-03-30 15:56:27.299518

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e194aa5ffae1'
down_revision: Union[str, Sequence[str], None] = '1a8b218ba8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_publishers_email'), 'publishers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishers_email'), table_name='publishers')
    # ### end Alembic commands ###
